# -*- coding: utf-8 -*-
"""Armstrong_sayı.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1WzN7VFRiYFkGX-rFho7PhXUFzjxHvF_Y

#Bir sayının Armstrong Sayı olup olmadığını gösteren program.
"""

number = int(input("Pozitif bir sayı giriniz"))
total = 0
for test in str(number):
    total = total + (int(test) ** len(str(number)))

if (total == number):
     print("Bu sayı armstrong sayısıdır. ")
else:
     print("Bu sayı armstrong sayısı değildir.")