# -*- coding: utf-8 -*-
"""fibonacci.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r1EffPgAfhldaEDIyax6lBsm0wkRGdTL

#1'den 55'e kadar olan Fibonacci sayılarını yazdıran  python kodu
"""

fibonacci = [1,1]
while 55 not in fibonacci :
	fibonacci_1 = fibonacci[-1] +fibonacci[-2]
	fibonacci.apend(fibonacci_1)
print(fibonacci)