# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wLNhwSxlaxhXYNDenB4ZamC30BlydnWU

#Fizz Buzz , temel programlama becerilerini test etmek için röportajlarda kullanılan ünlü bir kod mücadelesidir. 
1'den 100'e kadar sayıları
yazdırın :
Bir sayı 3'ün katıysa bu sayının yerine "Fizz" yazdırın,
Bir sayı 5'in katıysa, bu sayı yerine "Buzz" yazdırın,
Hem 3 hem de 5'in katı olan sayılar için "FizzBuzz" yazdırın,kalan sayıları değişmeden yazdırın. """

for number in range(1,101):
  if number % 3 == 0 and number % 5 == 0:
    print("FizzBuzz")
  elif number % 3 == 0:
    print("Fizz")
  elif number % 5 == 0:
    print("Buzz")
  else:
    print(number)