# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ECGjBxR5uET-ijHf3Z7g-6s_RTz3B89h

#Girilen cümlelerdeki harf veya karakter sayısını hesaplama:
"""

sentence = str(input(" Enter a sentence: "))
for letter in sentence:
    if not letter in words:
        words+=letter
        print("'{}' :  {} ".format(letter, sentence.count(letter)))

